version: '1.0'

services:
  zookeeper-server:
    container_name: 'zookeeper-server'
    image: bitnami/zookeeper:latest
    networks:
      - kafka-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka-server:
    container_name: 'kafka-server'
    image: bitnami/kafka:latest
    networks:
      - kafka-network
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
    ports:
      - 9092:9092

  init-kafka:
    container_name: 'init-kafka'
    image: bitnami/kafka:latest
    networks:
      - kafka-network
    depends_on:
      - kafka-server
    entrypoint: [ '/bin/sh', '-c' ]
    command: "kafka-topics.sh --create --bootstrap-server kafka-server:9092 --replication-factor 1 --partitions 3 --topic tweets"

networks:
  kafka-network:
    name: kafka-network